version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - node-service
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - fullstack-net

  node-service:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - db
    networks:
      - fullstack-net

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - fullstack-net

networks:
  fullstack-net:

volumes:
  db-data: